# src/Wifi/WifiInfoBundle/Resources/config/routing.yml
WifiTrackingBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: WifiTrackingWifiInfoBundle:Default:index }
WifiTrackingBundle_getInfo:
    pattern:  /wifi
    defaults: { _controller: WifiTrackingWifiInfoBundle:Default:get, _format: ~ }
WifiTrackingBundle_createInfo:
    pattern:  /wifi/create
    defaults: { _controller: WifiTrackingWifiInfoBundle:Default:createWifi, _format: ~ }
WifiTrackingBundle_updateInfo:
    pattern:  /wifi/update
    defaults: { _controller: WifiTrackingWifiInfoBundle:Default:updateWifi, _format: ~ }
WifiTrackingBundle_getUpdateInfo:
    pattern:  /wifi/get-update
    defaults: { _controller: WifiTrackingWifiInfoBundle:Default:getWifiStore, _format: ~ }
