<?php

namespace WifiTracking\WifiInfoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WifiInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WifiInfoRepository extends EntityRepository
{
}
