WifiTracking\WifiInfoBundle\Entity\WifiPasswordListStore:
    type: entity
    table: null
    fields:
       id:
          type: integer
          id: true
          generator:
             strategy: AUTO
       wifiName:
          type: string
          length: 255
          column: wifi_name
       wifiPass:
           type: string
           length: 255
           column: wifi_pass
    manyToOne:
      wifi:
        targetEntity: WifiTracking\WifiInfoBundle\Entity\WifiInfo
        joinColumn:
          name: wifi_id
          referencedColumnName: id