profile_homepage:
    path:     /hello/{name}
    defaults: { _controller: ProfileBundle:Default:index }
profile_login:
    path:     /login
    defaults: { _controller: ProfileBundle:Default:login }
